"""Add_name_and_filetype

Revision ID: 3fea1fc82725
Revises: 6bb80a77bb32
Create Date: 2025-12-22 18:37:10.071632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fea1fc82725'
down_revision: Union[str, None] = '6bb80a77bb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(), nullable=True))
    op.add_column('images', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'file_type')
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
