"""Add_image_telemetry

Revision ID: 6bb80a77bb32
Revises: 363e81e49d08
Create Date: 2025-12-22 18:02:15.224741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb80a77bb32'
down_revision: Union[str, None] = '363e81e49d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    op.add_column('images', sa.Column('applied_steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('images', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'processing_time_ms')
    op.drop_column('images', 'applied_steps')
    op.drop_column('images', 'confidence_scores')
    # ### end Alembic commands ###
