name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'   
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -f -X GET "https://dam-be.onrender.com/health" || curl -f -X GET "https://dam-be.onrender.com/api/v1/health"
          
      - name: Ping fallback (just in case)
        if: failure()
        run: |
          curl -f -X GET "https://dam-be.onrender.com/" || echo "All pings failed, but workflow still ran"
